spring:
  application.name: weather-aggregator

active-client:
  type: "all" # Correct values ['all', 'visual-crossing', 'weather-api']

visual-crossing:
  url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/weatherdata/forecast"
  apiKey: "GC22RFQA88SUEPL9HZUMG8WNR"
  aggregateHours: "24"
  unitGroup: "metric"
  contentType: "json"

weather-api:
  url: "http://api.weatherapi.com/v1/forecast.json"
  apiKey: "4277c7de4c5e44a0ae5192833242805"
  language: "ru"

thread-pool-config:
  core-pool-size: 3
  max-pool-size: 3
  queue-capacity: 100
